In [1]:
import numpy as np


In [3]:
a = np.array([1,2,3,4, "hello"])
print(a)

['1' '2' '3' '4' 'hello']


In [4]:
a.shape

(5,)

In [5]:
b =  np.array([[1],[2],[2],[2]])
b.shape

(4, 1)

In [6]:
c = np.array([[1,2,3], [4,5,6]])

In [7]:
print(c)

[[1 2 3]
 [4 5 6]]


In [8]:
c.shape

(2, 3)

In [16]:
a = np.full((3,2),5)
print(a)

[[5 5]
 [5 5]
 [5 5]]


In [47]:
c = np.eye(4)
randommat = np.random.random((3,4))
print(randommat)
randommat=np.zeros((3,4), dtype=np.int64)
print(randommat)

[[0.06999145 0.96005913 0.33386044 0.33798648]
 [0.55886569 0.20728683 0.19563423 0.40087315]
 [0.82061252 0.63687339 0.93073571 0.17854941]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [48]:

randommat[0:,-1] = 7
randommat[:-1, 0:2]=1
print(randommat.dtype)

int64


In [49]:
x=np.array([[1,2], [3,4]])
y=np.array([[1,2], [3,4]])

In [50]:
x+y

array([[2, 4],
       [6, 8]])

In [51]:
np.add(x,y)

array([[2, 4],
       [6, 8]])

In [56]:
x*y
###element wise multiply

array([[ 1,  4],
       [ 9, 16]])

In [57]:
np.dot(x,y)

array([[ 7, 10],
       [15, 22]])

In [59]:
x.dot(y)

array([[ 7, 10],
       [15, 22]])

In [70]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
a.dot(b)

30

In [71]:
print(np.sum(x, axis=1))

[3 7]


In [73]:
print(a)
b=b**2
print(b)
c=np.stack((a,b), axis=0)
print(c)

[1 2 3 4]
[  1  16  81 256]
[[  1   2   3   4]
 [  1  16  81 256]]


In [80]:
c = c.reshape((-1,2))
print(c)

[[  1   2]
 [  3   4]
 [  1  16]
 [ 81 256]]


In [85]:
a =  np.arange(10) +5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [87]:
np.random.shuffle(a)
print(a)

[ 8  7 13 14 10  9  5  6 11 12]


In [90]:
np.random.shuffle(a)
print(a)

[ 7 11 13  6 12 10 14  8  9  5]


In [101]:
a = np.random.randint(100,200, 10)
b = np.random.choice([100,34,34,5,4,23,23,200, 10])
print(a)
print(b)

[177 194 124 158 191 199 171 126 167 193]
10


In [106]:
a=np.array([[1,2,3,4],[1,2,3,4]])
np.min(a)

1

In [116]:
b=np.array([0,1,2,3,4])
np.mean(b)
print(np.mean(a, axis=0))
np.median(b)

[1. 2. 3. 4.]


2.0

In [118]:
wts= np.array([1,2,3,4,5])
print(np.average(b,weights=wts))

2.6666666666666665


In [120]:
np.var(a)

1.25